<?php

namespace ReclamationBundle\Repository;

/**
 * ReclamationPrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationPrestationRepository extends \Doctrine\ORM\EntityRepository
{
}
