<?php

namespace AppBundle\Repository;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationPrestationRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercheMarque($rec,$id)
    {
        $q=$this->getEntityManager()->createQuery("select v from AppBundle:ReclamationPrestation v where 
            v.idUser=:id and v.description like :rec")
            ->setParameter('rec', '%'.$rec.'%')->setParameter(':id',$id);
        return $q->getResult();

    }
}
